services:
  ec2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3022:22"
      - "2375:2375"
    volumes:
      - ec2_data:/home/ubuntu
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g
        reservations:
          cpus: '0.5'
          memory: 512m
    security_opt:
      - seccomp:unconfined
    privileged: true

volumes:
  ec2_data:
    driver: local